"""Add lottery data tables and stats

Revision ID: 94fc2456d3ec
Revises: a0eaaee46b3a
Create Date: 2026-02-24 11:56:51.729685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fc2456d3ec'
down_revision: Union[str, Sequence[str], None] = 'a0eaaee46b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computed_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_computed_statistics_game_type'), 'computed_statistics', ['game_type'], unique=False)
    op.create_index(op.f('ix_computed_statistics_metric_name'), 'computed_statistics', ['metric_name'], unique=False)
    op.create_table('draws_cashpop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draws_cashpop_draw_datetime'), 'draws_cashpop', ['draw_datetime'], unique=True)
    op.create_table('draws_fantasy5',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('numbers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draws_fantasy5_draw_datetime'), 'draws_fantasy5', ['draw_datetime'], unique=True)
    op.create_table('draws_pick3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('digit_1', sa.Integer(), nullable=False),
    sa.Column('digit_2', sa.Integer(), nullable=False),
    sa.Column('digit_3', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draws_pick3_draw_datetime'), 'draws_pick3', ['draw_datetime'], unique=True)
    op.create_table('draws_pick4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('digit_1', sa.Integer(), nullable=False),
    sa.Column('digit_2', sa.Integer(), nullable=False),
    sa.Column('digit_3', sa.Integer(), nullable=False),
    sa.Column('digit_4', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draws_pick4_draw_datetime'), 'draws_pick4', ['draw_datetime'], unique=True)
    op.create_table('draws_pick5',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('digit_1', sa.Integer(), nullable=False),
    sa.Column('digit_2', sa.Integer(), nullable=False),
    sa.Column('digit_3', sa.Integer(), nullable=False),
    sa.Column('digit_4', sa.Integer(), nullable=False),
    sa.Column('digit_5', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draws_pick5_draw_datetime'), 'draws_pick5', ['draw_datetime'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draws_pick5_draw_datetime'), table_name='draws_pick5')
    op.drop_table('draws_pick5')
    op.drop_index(op.f('ix_draws_pick4_draw_datetime'), table_name='draws_pick4')
    op.drop_table('draws_pick4')
    op.drop_index(op.f('ix_draws_pick3_draw_datetime'), table_name='draws_pick3')
    op.drop_table('draws_pick3')
    op.drop_index(op.f('ix_draws_fantasy5_draw_datetime'), table_name='draws_fantasy5')
    op.drop_table('draws_fantasy5')
    op.drop_index(op.f('ix_draws_cashpop_draw_datetime'), table_name='draws_cashpop')
    op.drop_table('draws_cashpop')
    op.drop_index(op.f('ix_computed_statistics_metric_name'), table_name='computed_statistics')
    op.drop_index(op.f('ix_computed_statistics_game_type'), table_name='computed_statistics')
    op.drop_table('computed_statistics')
    # ### end Alembic commands ###
